# Generated by Django 5.0.7 on 2024-08-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="done",
            field=models.CharField(
                choices=[("doing", "Doing"), ("done", "Done")], max_length=5
            ),
        ),
    ]
